config/routes.rb
# frozen_string_literal: true

require "routes_constraint/admin"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  constraints(-> { _1.subdomain.present? }) do
    match "(*path)", via: :all, to: "subdomains#redirect", format: false
  end

  constraints(-> { _1.env["mee.organization_id"] }) do
    root to: "welcome#index"

    resource :membership, only: [:show, :create, :update]

    ## User profile section routes
    resource :profile, only: :show

    resources :patients, except: [:edit, :update], constraints: { id: /.+/ } do
      resources :pipelines, only: [:index, :new, :create]
      scope module: :patients do
        resource :details, only: :show
        post "inputs", to: "files#create", as: :inputs
      end
    end

    resources :comparisons, only: [:index]

    resources :pipelines do
      scope module: :pipelines do
        resource :file_browsers, only: :show
        resource :files, only: :show
        post "inputs", to: "files#create", as: :inputs
      end
    end

    resources :computations, only: [:show, :update] do
      scope module: :computations do
        resource :actions, only: :show
        resource :abort, only: [:create]
        resource :stdout, only: :show
        resource :stderr, only: :show
        get "files/:secret/type/:type", to: "files#show_by_type", as: :type_inputs
        get "files/:secret/filename/:filename", constraints: { filename: /.*/ }, to: "files#show_by_filename", as: :filename_inputs
        post "files/:secret", to: "files#create", as: :outputs
        resource :artifacts, only: :show, path: "artifacts/:secret/:name", constraints: { name: /.*/ }
        resource :artifacts, only: :create, path: "artifacts/:secret", as: :upload_artifact
      end
    end

    get "steps/*step_id/versions", to: "steps/versions#index", as: :step_versions

    resources :artifacts, only: :index
    post "artifacts_upload", to: "artifacts#upload", as: :upload_artifact

    scope module: :organizations do
      resources :artifacts, only: [:edit, :update]
      get "files/:file_id/artifacts/new", to: "artifacts#new", as: :new_artifact_from_file
      post "files/:file_id/artifacts", to: "artifacts#create", as: :create_artifact_from_file
    end

    # Help
    get "help" => "help#index"
    get "help/:category/:file" => "help#show",
        as: :help_page,
        constraints: { category: /.*/, file: %r{[^/.]+} }

    resources :parameters, only: :show

    resources :flows, except: :show do
      scope module: :flows do
        resource :pipeline_parameters, only: :show
      end
    end
    resources :steps, except: :show do
      scope module: :steps do
        resources :git_configs, only: [:index, :show]
      end
    end

    resources :cohorts do
      scope module: :cohorts do
        resources :patients, only: [:destroy, :create, :index]
        resources :campaigns, only: [:index]
      end
    end

    post "patients/upload", to: "patients/uploads#create", as: :upload_patients

    resources :campaigns, except: [:edit, :update] do
      scope module: :campaigns do
        resource :run, only: :create
      end
    end

    namespace :admin do
      resources :users
      resource :organization, only: [:show, :update, :destroy] do
        scope module: :organizations do
          resources :git_configs, only: :show
        end
      end
      resources :grants, except: :show
      resources :licenses, except: :show
      resources :data_file_types, except: :show
    end

    delete "files/*id",
           to: "files#destroy",
           constraints: { id: /.*/ },
           as: :file
  end

  constraints(-> { !_1.env["mee.organization_id"] }) do
    root to: "home#index", as: :home_root
    resources :home, only: [:index]
    resources :organizations, only: [:new, :create]
    namespace :organizations do
      resources :git_configs, only: :show
    end

    get "organization_not_found", to: "home#not_found", as: :organization_not_found
    get "organization_not_authorized", to: "home#not_authorized", as: :organization_not_authorized

    # TODO
    # # Sidekiq monitoring
    constraints(RoutesConstraint::Admin) do
      require "sidekiq/web"
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        resources :jobs, only: :index
      end
    end
  end

  constraints(-> { _1.subdomain.blank? }) do
    delete "logout", to: "sessions#destroy", as: "logout"
    match "auth/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "auth/failure", to: redirect("/")
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end
# rubocop:enable Metrics/BlockLength

app/models/membership.rb
# frozen_string_literal: true

class Membership < ApplicationRecord
  include Organizations::Roles, OrganizationUnit

  enum state: [:new_account, :approved, :blocked]

  delegate :name, :email, to: :user

  belongs_to :user

  validates :user, presence: true, uniqueness: { scope: :organization }
  validates :organization, presence: true

  scope :approved, -> { where(state: :approved) }
  scope :new_accounts, -> { where(state: :new_account) }
  scope :blocked, -> { where(state: :blocked) }

  def self.any_role(*roles)
    (arel_table[:roles_mask] & mask_for(roles)).gt(0)
  end
end

app/controllers/memberships_controller.rb
# frozen_string_literal: true

class MembershipsController < ApplicationController
  skip_before_action :authorize_membership!
  layout "memberships"

  def show
    if Current.membership.nil?
      render :not_a_member
    elsif Current.membership.blocked?
      render :blocked
    elsif Current.membership.new_account?
      render :new_account
    else
      redirect_to root_path
    end
  end

  def create
    if Membership.create(user: Current.user, organization:)
      flash.now[:notice] = "Join request created"
      render :new_account
    else
      flash.now[:error] = "Unable to create join request"
      render :not_a_member
    end
  end

  def update
    @membership = Current.membership
    if @membership.update_attribute(:dataverse_token, params[:membership][:dataverse_token])
      flash[:notice] = I18n.t("profiles.show.dataverse.updated")
      redirect_to profile_path
    end
  end
end

app/views/memberships/_footer.html.haml
%p
  If you have any additional questions please
  = link_to "contact us.", "mailto:dice@cyfronet.pl"
%h2
  = button_to logout_path, method: :delete do
    %i.fas.fa-sign-out-alt
    = t('logout')

app/views/memberships/_form.html.haml
= simple_form_for Current.membership do |form|
  %ul.list-group.mb-4
    %li.list-group-item
      = form.input :dataverse_token, as: :showable_secret, label: t("profiles.show.dataverse.label"),
        hint: "#{t("profiles.show.dataverse.hint")}#{link_to(t("profiles.show.dataverse.link"), help_page_path("manual", "dataverse"), class: "btn-link")}".html_safe
      = form.submit t("profiles.show.dataverse.submit"), class: "btn btn-sm btn-primary"

app/views/memberships/blocked.html.haml
%h1 You have no access to this Organization
%h2
  Your have not been granted access to #{Current.organization.name} organization.
  %br
  Please check if you're a member of this organization in
  %a{ href: "https://portal.plgrid.pl/team/my-team-index" }
    your PLGrid teams
  or contact organization administrators.

= render "memberships/footer"

app/views/memberships/new_account.html.haml
%h1 Join request registered
%h2
  Your request to join #{Current.organization.name} organization
  is registered and waiting for organization administrators'
  approval

= render "memberships/footer"

app/views/memberships/not_a_member.html.haml
%h1 You are not a member of this organization
%h2
  If you would like to join #{Current.organization.name} organization
  please click the link bellow:
  %p
    = link_to "Join organization", membership_path,
      method: :post, class: "btn btn-primary"
%p
  Your join request will be validated by the organization administrators.
  After successful approval you will be able to access this organization.

= render "memberships/footer"