config/routes.rb
# frozen_string_literal: true

require "routes_constraint/admin"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  constraints(-> { _1.subdomain.present? }) do
    match "(*path)", via: :all, to: "subdomains#redirect", format: false
  end

  constraints(-> { _1.env["mee.organization_id"] }) do
    root to: "welcome#index"

    resource :membership, only: [:show, :create, :update]

    ## User profile section routes
    resource :profile, only: :show

    resources :patients, except: [:edit, :update], constraints: { id: /.+/ } do
      resources :pipelines, only: [:index, :new, :create]
      scope module: :patients do
        resource :details, only: :show
        post "inputs", to: "files#create", as: :inputs
      end
    end

    resources :comparisons, only: [:index]

    resources :pipelines do
      scope module: :pipelines do
        resource :file_browsers, only: :show
        resource :files, only: :show
        post "inputs", to: "files#create", as: :inputs
      end
    end

    resources :computations, only: [:show, :update] do
      scope module: :computations do
        resource :actions, only: :show
        resource :abort, only: [:create]
        resource :stdout, only: :show
        resource :stderr, only: :show
        get "files/:secret/type/:type", to: "files#show_by_type", as: :type_inputs
        get "files/:secret/filename/:filename", constraints: { filename: /.*/ }, to: "files#show_by_filename", as: :filename_inputs
        post "files/:secret", to: "files#create", as: :outputs
        resource :artifacts, only: :show, path: "artifacts/:secret/:name", constraints: { name: /.*/ }
        resource :artifacts, only: :create, path: "artifacts/:secret", as: :upload_artifact
      end
    end

    get "steps/*step_id/versions", to: "steps/versions#index", as: :step_versions

    resources :artifacts, only: :index
    post "artifacts_upload", to: "artifacts#upload", as: :upload_artifact

    scope module: :organizations do
      resources :artifacts, only: [:edit, :update]
      get "files/:file_id/artifacts/new", to: "artifacts#new", as: :new_artifact_from_file
      post "files/:file_id/artifacts", to: "artifacts#create", as: :create_artifact_from_file
    end

    # Help
    get "help" => "help#index"
    get "help/:category/:file" => "help#show",
        as: :help_page,
        constraints: { category: /.*/, file: %r{[^/.]+} }

    resources :parameters, only: :show

    resources :flows, except: :show do
      scope module: :flows do
        resource :pipeline_parameters, only: :show
      end
    end
    resources :steps, except: :show do
      scope module: :steps do
        resources :git_configs, only: [:index, :show]
      end
    end

    resources :cohorts do
      scope module: :cohorts do
        resources :patients, only: [:destroy, :create, :index]
        resources :campaigns, only: [:index]
      end
    end

    post "patients/upload", to: "patients/uploads#create", as: :upload_patients

    resources :campaigns, except: [:edit, :update] do
      scope module: :campaigns do
        resource :run, only: :create
      end
    end

    namespace :admin do
      resources :users
      resource :organization, only: [:show, :update, :destroy] do
        scope module: :organizations do
          resources :git_configs, only: :show
        end
      end
      resources :grants, except: :show
      resources :licenses, except: :show
      resources :data_file_types, except: :show
    end

    delete "files/*id",
           to: "files#destroy",
           constraints: { id: /.*/ },
           as: :file
  end

  constraints(-> { !_1.env["mee.organization_id"] }) do
    root to: "home#index", as: :home_root
    resources :home, only: [:index]
    resources :organizations, only: [:new, :create]
    namespace :organizations do
      resources :git_configs, only: :show
    end

    get "organization_not_found", to: "home#not_found", as: :organization_not_found
    get "organization_not_authorized", to: "home#not_authorized", as: :organization_not_authorized

    # TODO
    # # Sidekiq monitoring
    constraints(RoutesConstraint::Admin) do
      require "sidekiq/web"
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        resources :jobs, only: :index
      end
    end
  end

  constraints(-> { _1.subdomain.blank? }) do
    delete "logout", to: "sessions#destroy", as: "logout"
    match "auth/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "auth/failure", to: redirect("/")
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end
# rubocop:enable Metrics/BlockLength

app/controllers/admin/data_file_types_controller.rb
# frozen_string_literal: true

class Admin::DataFileTypesController < ApplicationController
  before_action :load_and_authorize, only: [:edit, :update, :destroy]

  def index
    authorize(DataFileType)
    @pagy, @data_file_types = pagy(policy_scope(DataFileType))
  end

  def new
    @data_file_type = DataFileType.new
    authorize(@data_file_type)
  end

  def create
    @data_file_type = DataFileType.new(permitted_attributes(DataFileType).
                                       merge(organization: Current.organization))
    authorize(@data_file_type)

    if @data_file_type.save
      redirect_to(admin_data_file_types_path)
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    if @data_file_type.update(permitted_attributes(@data_file_type))
      redirect_to(admin_data_file_types_path)
    else
      render(:edit, status: :bad_request)
    end
  end

  def destroy
    @data_file_type.destroy
    redirect_to(admin_data_file_types_path)
  end

  private
    def load_and_authorize
      @data_file_type = Current.organization.data_file_types.find(params[:id])
      authorize(@data_file_type)
    end
end

app/views/admin/data_file_types/_data_file_type.html.haml
.card.mb-2
  .card-header
    = data_file_type.name
    (<code>#{data_file_type.pattern_preview}</code>)
    - if data_file_type.viewer
      \: #{data_file_type.viewer}
    .float-right.d-inline-flex
      - if policy(data_file_type).edit?
        = link_to edit_admin_data_file_type_path(data_file_type),
          title: t(".edit"), class: "edit mr-2 pr-2 border-right" do
          %i.fas.fa-edit

      - if policy(data_file_type).destroy?
        = button_to admin_data_file_type_path(data_file_type),
          form: { "data-turbo-confirm": t("are_you_sure") },
          method: :delete,
          title: t(".destroy"),
          class: "btn btn-sm btn-link delete p-0 m-0" do
          %i.fas.fa-trash

app/views/admin/data_file_types/_form.html.haml
= simple_form_for([:admin, data_file_type]) do |f|
  = f.error_notification
  .row
    .col-4.pr-5
      %h2= t ".general.title"
      %p.text-muted= t ".general.description_html"
    .col-8
      = f.input :data_type
      = f.input :name

  %hr
  .row.mt-4
    .col-4.pr-5
      %h2= t ".pattern.title"
      %p.text-muted= t ".pattern.description_html"
      = link_to t(".pattern.test_pattern"),
        "https://rubular.com/",
        class: "btn btn-primary btn-sm"
    .col-8
      = f.input :pattern

  %hr
  .row.mt-4
    .col-4.pr-5
      %h2= t ".viewer.title"
      %p.text-muted= t ".viewer.description"
    .col-8
      = f.input :viewer, collection: DataFileType.viewers

  %hr
  .row.mt-4
    .col-8.offset-4
      = link_to t("cancel"), admin_data_file_types_path,
        class: "btn btn-secondary"
      = f.button :submit, class: "btn btn-success"

app/views/admin/data_file_types/edit.html.haml
%h1= t '.title'

.card.mb-3
  .card-body
    = render partial: 'form', locals: { data_file_type: @data_file_type }

app/views/admin/data_file_types/index.html.haml
- if @data_file_types.size.zero?
  = render "layouts/empty",
    scope: "admin.data_file_types.empty",
    action_url: new_admin_data_file_type_path,
    image: "dft.svg"

- else
  %h1
    .float-left
      = t ".title"
    .float-right
      = link_to new_admin_data_file_type_path, class: "btn btn-success" do
        %i.fas.fa-plus
        = t ".add"
    .clearfix

  .card.mb-3
    .card-body
      = render @data_file_types
      -if @pagy.pages != 1
        != pagy_bootstrap_nav(@pagy)

app/views/admin/data_file_types/new.html.haml
%h1= t '.title'

.card.mb-3
  .card-body
    = render partial: 'form', locals: { data_file_type: @data_file_type }