config/routes.rb
# frozen_string_literal: true

require "routes_constraint/admin"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  constraints(-> { _1.subdomain.present? }) do
    match "(*path)", via: :all, to: "subdomains#redirect", format: false
  end

  constraints(-> { _1.env["mee.organization_id"] }) do
    root to: "welcome#index"

    resource :membership, only: [:show, :create, :update]

    ## User profile section routes
    resource :profile, only: :show

    resources :patients, except: [:edit, :update], constraints: { id: /.+/ } do
      resources :pipelines, only: [:index, :new, :create]
      scope module: :patients do
        resource :details, only: :show
        post "inputs", to: "files#create", as: :inputs
      end
    end

    resources :comparisons, only: [:index]

    resources :pipelines do
      scope module: :pipelines do
        resource :file_browsers, only: :show
        resource :files, only: :show
        post "inputs", to: "files#create", as: :inputs
      end
    end

    resources :computations, only: [:show, :update] do
      scope module: :computations do
        resource :actions, only: :show
        resource :abort, only: [:create]
        resource :stdout, only: :show
        resource :stderr, only: :show
        get "files/:secret/type/:type", to: "files#show_by_type", as: :type_inputs
        get "files/:secret/filename/:filename", constraints: { filename: /.*/ }, to: "files#show_by_filename", as: :filename_inputs
        post "files/:secret", to: "files#create", as: :outputs
        resource :artifacts, only: :show, path: "artifacts/:secret/:name", constraints: { name: /.*/ }
        resource :artifacts, only: :create, path: "artifacts/:secret", as: :upload_artifact
      end
    end

    get "steps/*step_id/versions", to: "steps/versions#index", as: :step_versions

    resources :artifacts, only: :index
    post "artifacts_upload", to: "artifacts#upload", as: :upload_artifact

    scope module: :organizations do
      resources :artifacts, only: [:edit, :update]
      get "files/:file_id/artifacts/new", to: "artifacts#new", as: :new_artifact_from_file
      post "files/:file_id/artifacts", to: "artifacts#create", as: :create_artifact_from_file
    end

    # Help
    get "help" => "help#index"
    get "help/:category/:file" => "help#show",
        as: :help_page,
        constraints: { category: /.*/, file: %r{[^/.]+} }

    resources :parameters, only: :show

    resources :flows, except: :show do
      scope module: :flows do
        resource :pipeline_parameters, only: :show
      end
    end
    resources :steps, except: :show do
      scope module: :steps do
        resources :git_configs, only: [:index, :show]
      end
    end

    resources :cohorts do
      scope module: :cohorts do
        resources :patients, only: [:destroy, :create, :index]
        resources :campaigns, only: [:index]
      end
    end

    post "patients/upload", to: "patients/uploads#create", as: :upload_patients

    resources :campaigns, except: [:edit, :update] do
      scope module: :campaigns do
        resource :run, only: :create
      end
    end

    namespace :admin do
      resources :users
      resource :organization, only: [:show, :update, :destroy] do
        scope module: :organizations do
          resources :git_configs, only: :show
        end
      end
      resources :grants, except: :show
      resources :licenses, except: :show
      resources :data_file_types, except: :show
    end

    delete "files/*id",
           to: "files#destroy",
           constraints: { id: /.*/ },
           as: :file
  end

  constraints(-> { !_1.env["mee.organization_id"] }) do
    root to: "home#index", as: :home_root
    resources :home, only: [:index]
    resources :organizations, only: [:new, :create]
    namespace :organizations do
      resources :git_configs, only: :show
    end

    get "organization_not_found", to: "home#not_found", as: :organization_not_found
    get "organization_not_authorized", to: "home#not_authorized", as: :organization_not_authorized

    # TODO
    # # Sidekiq monitoring
    constraints(RoutesConstraint::Admin) do
      require "sidekiq/web"
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        resources :jobs, only: :index
      end
    end
  end

  constraints(-> { _1.subdomain.blank? }) do
    delete "logout", to: "sessions#destroy", as: "logout"
    match "auth/:provider/callback", to: "sessions#create", via: [:get, :post]
    get "auth/failure", to: redirect("/")
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end
# rubocop:enable Metrics/BlockLength

app/models/concerns/organizations/roles.rb
# frozen_string_literal: true

module Organizations
  module Roles
    extend ActiveSupport::Concern

    ROLES = [:admin]

    included do
      include RoleModel
      roles ROLES
    end

    class_methods do
      def admins
        where(any_role(:admin))
      end

      def any_role(*roles)
        (arel_table[:roles_mask] & mask_for(roles)).gt(0)
      end
    end
  end
end

app/models/organization.rb
# frozen_string_literal: true

require "friendly_id_error_mover"

class Organization < ApplicationRecord
  extend FriendlyId
  include InputsStub

  friendly_id :name, use: [:slugged, FriendlyIdErrorMover]

  include Licenses
  include Steps
  include Git

  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :approved_users,
           -> { where(memberships: { state: :approved }) },
           through: :memberships,
           source: "user"

  has_many :patients, dependent: :destroy
  has_many :flows, dependent: :destroy
  has_many :grants, dependent: :destroy
  has_many :data_file_types, dependent: :destroy do
    def find_by_filename(filename)
      detect { |dft| dft.match?(filename) }
    end
  end
  has_many :pipelines, as: :runnable, dependent: :destroy
  has_many_attached :artifacts
  has_many :cohorts, dependent: :destroy
  has_many :campaigns, dependent: :destroy

  has_one_attached :logo, service: :local

  validates :name, presence: true
  validates :plgrid_team_id, presence: true
  validates :storage_quota, presence: true
  validates :dataverse_url, allow_blank: true, format: URI.regexp(%w[http https])

  include Errorable

  def copy_slug_error_to_name
    if errors[:friendly_id].present?
      errors.add(:name, errors[:friendly_id].first)
    end
  end

  def organization
    self
  end

  def organization_id
    id
  end

  def pick_file_by_type(type)
    nil
  end

  def pick_file_by_filename(type)
    nil
  end

  def quota
    StorageQuota.new(self)
  end

  def validate_later
    Organization::ValidateTokenJob.perform_later(self) if git_uses_private_token?
    steps.find_each do |step|
      Step::ValidateRepositoryJob.perform_later(step)
    end
  end
end

app/models/organization/git.rb
# frozen_string_literal: true

module Organization::Git
  extend ActiveSupport::Concern
  include GitAttributes

  included do
    serialize :git_config, GitConfig
    validates_associated :git_config
    validates :git_config, presence: { message: "creation failed. Attributes are missing or wrong" }
  end

  def git_uses_private_token?
    self.git_config.attributes.include?("private_token")
  end
end

app/models/organization/inputs_stub.rb
# frozen_string_literal: true

module Organization::InputsStub
  extend ActiveSupport::Concern

  def inputs_blobs
    ActiveStorage::Blob.none
  end
end

app/models/organization/licenses.rb
# frozen_string_literal: true

module Organization::Licenses
  extend ActiveSupport::Concern

  included do
    has_many :licenses, dependent: :destroy
  end

  def license_for(type)
    licenses.active.find_by(name: type)
  end
end

app/models/organization/steps.rb
# frozen_string_literal: true

module Organization::Steps
  extend ActiveSupport::Concern

  included do
    has_many :steps, dependent: :destroy
  end
end

app/models/organization/storage_quota.rb
# frozen_string_literal: true


class Organization::StorageQuota
  attr_reader :organization
  def initialize(organization)
    @organization = organization
  end

  def usage
    Rails.cache.fetch(
      "#{organization.id}_storage_usage",
      expires_in: 1.minute) {
      calculate_usage.round(2)
    }
  end

  def percentage_used
    Percentage.new(usage, organization.storage_quota).to_f
  end

  def limit
    @organization.storage_quota
  end

  def exceeded?
    usage > limit
  end

  private
    def calculate_usage
      pipelines = Pipeline.where(runnable: [organization, organization.patients])
      ActiveStorage::Blob.where(
        attachments: ActiveStorage::Attachment.where(
          record: [organization, organization.patients, pipelines])
      ).sum(:byte_size) / 1024.0**3 # change to GB
    end
end

app/models/user/organizations.rb
# frozen_string_literal: true

module User::Organizations
  extend ActiveSupport::Concern

  included do
    has_many :memberships, dependent: :destroy
    has_many :organizations, through: :memberships
  end

  class_methods do
    def approved_in(organization)
      joins(:memberships).
        where(memberships: { organization:, state: :approved })
    end
  end
end

app/controllers/admin/organizations/git_configs_controller.rb
# frozen_string_literal: true

module Admin
  class Organizations::GitConfigsController < ApplicationController
    include GitConfigs

    before_action :find_and_authorize

    private
      def find_and_authorize
        @git_config = Current.organization.git_config
        authorize(Current.organization, :update?)
      end

      def module_type
        "organization"
      end
  end
end

app/controllers/admin/organizations_controller.rb
# frozen_string_literal: true

module Admin
  class OrganizationsController < ApplicationController
    include Organization::Params
    before_action { @organization = Current.organization }

    def show
      @organization.load_persistent_errors
      authorize(@organization)
    end

    def update
      authorize(@organization)

      if @organization.update(organization_params(@organization))
        flash[:notice] = I18n.t("admin.organizations.show.updated")
        redirect_to(admin_organization_path)
      else
        render(:show, status: :unprocessable_entity)
      end
    end

    def destroy
      authorize(@organization)
      @organization.destroy
      redirect_to(root_url(script_name: nil))
    end
  end
end

app/controllers/concerns/organization/authorize.rb
# frozen_string_literal: true

module Organization::Authorize
  extend ActiveSupport::Concern

  included do
    before_action :load_organization!
    before_action :authorize_membership!
  end

  def pundit_user
    UserContext.new(Current.user, Current.organization, Current.membership)
  end

  private
    def load_organization!
      Current.organization = Organization.find request.env["mee.organization_id"]
    rescue ActiveRecord::RecordNotFound
      raise Organization::NotFoundError
    end

    def authorize_membership!
      raise Membership::NotFoundError unless Current.membership
      raise Membership::BlockedError if Current.membership.blocked?
      raise Membership::NewError unless Current.membership.approved?
    end
end

app/controllers/concerns/organization/params.rb
# frozen_string_literal: true

module Organization::Params
  extend ActiveSupport::Concern

  private
    def organization_params(organization = Organization.new)
      permitted_attributes = policy(organization).permitted_attributes +
        [ git_config_attributes: permitted_git_config_attributes ]

      params.require(:organization).permit(permitted_attributes)
    end

    def permitted_git_config_attributes
      git_type = params.dig(:organization, :git_config_attributes, :git_type)
      git_config_class = GitConfig.by_type(git_type)

      policy(git_config_class).permitted_attributes if git_config_class
    end
end

app/controllers/organizations/artifacts_controller.rb
# frozen_string_literal: true

class Organizations::ArtifactsController < ApplicationController
  def new
    @file = ActiveStorage::Attachment.find(params[:file_id])
    @artifact = Artifact.new(attachment_id: params[:file_id], filename: @file.filename)
  end

  def create
    @artifact = Artifact.new(filename: params[:artifact][:filename], attachment_id: params[:file_id])
    @file = ActiveStorage::Attachment.find(params[:file_id])
    if @artifact.save
      flash.now[:notice] = t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @artifact = Artifact.find_by_id(params[:id])
  end

  def update
    @artifact = Artifact.find_by_id(params[:id])
    @file = @artifact.attachment
    if @artifact.update(filename: params.dig(:artifact, :filename))
      flash.now[:notice] = t(".success")
    else
      render :edit, status: :unprocessable_entity
    end
  end
end

app/controllers/organizations/git_configs_controller.rb
# frozen_string_literal: true

class Organizations::GitConfigsController < RootApplicationController
  include GitConfigs

  private
    def module_type
      "organization"
    end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < RootApplicationController
  include Organization::Params
  before_action :authenticate_user!

  def new
    @organization = Organization.new(git_config: GitConfig::Gitlab.new)
    authorize(@organization)
  end

  def create
    @organization = Organization.new(organization_params)
    authorize(@organization)

    @organization.memberships
      .build(user: Current.user, state: :approved, roles: [:admin])

    if @organization.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/views/layouts/organization/side_menu/_administration.html.haml
- if policy(User).manage_users? || policy(:job).show? || policy(:organization).show?
  %h6.sidebar-heading.d-flex.px-3.mt-4.mb-1.text-muted= t ".title"
  %ul.nav.flex-column.mb-2.ml-3
    - if policy(:organization).show?
      %li.nav-item
        = active_link_to admin_organization_path, class: "nav-link d-flex justify-content-between align-items-center" do
          %span
            = t(".organization")
          - unless organization_valid?
            .fa.fa-exclamation-triangle.d-flex.align-items-center.text-muted{ title: t(".organization_problem") }
    - if policy(DataFileType).index?
      %li.nav-item
        = active_link_to t(".data_file_types"), admin_data_file_types_path, class: "nav-link"
    - if policy(Grant).index?
      %li.nav-item
        = active_link_to t(".grants"), admin_grants_path, class: "nav-link"
    - if policy(License).index?
      %li.nav-item
        = active_link_to t(".licenses"), admin_licenses_path, class: "nav-link"
    - if policy(User).manage_users?
      %li.nav-item
        = active_link_to admin_users_path, class: "nav-link" do
          = t(".users")
          - if Current.organization.memberships.new_accounts.count.positive?
            %i.fa.fa-exclamation-triangle

app/views/layouts/organization/side_menu/_help.html.haml
%h6.sidebar-heading.d-flex.px-3.mt-4.mb-1.text-muted= t ".title"
%ul.nav.flex-column.mb-2.ml-3
  - help_items.each do |item|
    %li.nav-item
      = active_link_to item.title, help_page_path(category: item.category, file: item.file),
       class: "nav-link", title: item.description

app/views/layouts/organization/side_menu/_pipelines_blueprints.html.haml
- if policy(Patient).index? || policy(:files).index?
  %h6.sidebar-heading.d-flex.px-3.mt-4.mb-1.text-muted= t ".title"
%ul.nav.flex-column.mb-2.ml-3
  - if policy(Flow).index?
    %li.nav-item
      = active_link_to t(".flows"), flows_path, class: "nav-link"
  - if policy(Step).index?
    %li.nav-item
      = active_link_to steps_path, class: "nav-link d-flex justify-content-between align-items-center" do
        %span
          = t(".steps")

        - unless steps_valid?
          .fa.fa-exclamation-triangle.d-flex.align-items-center.text-muted{ title: t(".steps_problem") }

app/views/layouts/organization/side_menu/_research.html.haml
- if policy(Patient).index? || policy(:files).index?
  %h6.sidebar-heading.d-flex.px-3.mt-4.mb-1.text-muted= t ".title"

  %ul.nav.flex-column.mb-2.ml-3
    - if policy(Patient).index?
      %li.nav-item
        = active_link_to t(".patients"), patients_path, class: "nav-link"
    - if policy(Pipeline).index?
      %li.nav-item
        = active_link_to t(".pipelines"), pipelines_path, class: "nav-link"
      %li.nav-item
        = active_link_to t(".artifacts"), artifacts_path,class: "nav-link"
    - if policy(Cohort).index?
      %li.nav-item
        = active_link_to t(".cohorts"), cohorts_path, class: "nav-link"
    - if policy(Campaign).index?
      %li.nav-item
        = active_link_to t(".campaigns"), campaigns_path, class: "nav-link"

app/views/layouts/organization/side_menu/_storage_usage.html.haml
%h6.sidebar-heading.d-flex.px-3.mt-4.mb-1.text-muted= t(".title")
.mb-2.ml-3.mr-3
  = render StorageUsageBar.new
  - if Current.organization.quota.exceeded?
    %p.text-danger= t(".quota_exceeded")

app/views/layouts/organization/side_menu/_user.html.haml
.d-md-none
  %h6.sidebar-heading.d-flex.px-3.mt-4.mb-1.text-muted User
  %ul.nav.flex-column.mb-2.ml-3
    %li.nav-item
      = active_link_to t(".profile"), profile_path
    %li.nav-item
      = button_to t(".logout"), logout_path,
        method: :delete,
        class: "nav-link"